### ISSUE TITLE
Fan Control?

### ISSUE THREAD

**Issue by Bhavinjain260** [Levonhard/X515JA-Hackintosh#1]
Hey do I have same laptop vivobook x515ja but I configured the EFI myself and I have a fully working and stable system 
I wanted to know are you able to control or read the correct fan speed?

**Comment by Levonhard** [comment]
I'm a hackintosh newbie, so far I haven't been able to get the control and reading fan speed working.

In your hackintosh did you manage to make sleep mode to work?

**Comment by Bhavinjain260** [comment]
for now everything is working 
headphone + headphone mic (volume is a bit low on headphone and on speaker)
sleep works

**Comment by Bhavinjain260** [comment]
everything works except HDMI

**Comment by Bhavinjain260** [comment]
@Levonhard https://github.com/Bhavinjain260/Asus_Vivobook15_X515JA_Opencore

**Comment by chaikovskiy99** [comment]
> Hey do I have same laptop vivobook x515ja but I configured the EFI myself and I have a fully working and stable system I wanted to know are you able to control or read the correct fan speed?

Use AsusSMC kext, it allows you to get fan speed reading.
