### ISSUE TITLE
Need help regarding audio fix

### ISSUE THREAD

**Issue by ParampreetR** [Levonhard/X515JA-Hackintosh#2]
Firstly thanks for sharing EFI, it's working perfectly.

I'm at post-install procedures but unable to make audio working. My laptop has "Intel smart sound technology", hopefully you could have gone through the same. Plz help

**Comment by Levonhard** [comment]
Your laptop model is the same as mine? ASUS X515JA-EJ1792W?

If not, maybe your laptop model use another audio layout or another Realtek codec. My laptop use Realtek alc256 codec, and for MacOS I'm using AppleALC kext with audio layout set to 13.

**Comment by ParampreetR** [comment]
Mine is X515JA-X515JAB, thanks for reply. But later I found Intel smart sound technology isn't supported and any device connected through this will not work. 

Once again thanks for EFI 😃 I found this when I completely lost my hope of installing macOS on my laptop. Your EFI worked perfectly for me.

**Comment by chaikovskiy99** [comment]
> Mine is X515JA-X515JAB, thanks for reply. But later I found Intel smart sound technology isn't supported and any device connected through this will not work.
> 
> Once again thanks for EFI 😃 I found this when I completely lost my hope of installing macOS on my laptop. Your EFI worked perfectly for me.

I have same laptop, I managed to install through official dortania guide, but audio is erratic, it works sometimes, and sometimes it doesn't, layout id 13 also works for me, when it actually works. Also, have you fixed display scaling?

**Comment by ParampreetR** [comment]
> > Mine is X515JA-X515JAB, thanks for reply. But later I found Intel smart sound technology isn't supported and any device connected through this will not work.
> > Once again thanks for EFI 😃 I found this when I completely lost my hope of installing macOS on my laptop. Your EFI worked perfectly for me.
> 
> I have same laptop, I managed to install through official dortania guide, but audio is erratic, it works sometimes, and sometimes it doesn't, layout id 13 also works for me, when it actually works. Also, have you fixed display scaling?

Do you have exact same model? X515JA-X515JAB? 
I didn't faced any issues regarding display scalling, it worked fine with this EFI. 
Small confirmation, do your laptop have C-Media sound card?

**Comment by Levonhard** [comment]
> > Mine is X515JA-X515JAB, thanks for reply. But later I found Intel smart sound technology isn't supported and any device connected through this will not work.
> > Once again thanks for EFI 😃 I found this when I completely lost my hope of installing macOS on my laptop. Your EFI worked perfectly for me.
> 
> I have same laptop, I managed to install through official dortania guide, but audio is erratic, it works sometimes, and sometimes it doesn't, layout id 13 also works for me, when it actually works. Also, have you fixed display scaling?

Just like @ParampreetR, I didn't face any issue regarding display scaling.
As for audio issue if you have the same Realtek codec as mine, which is ALC256, you can try another layout id.
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs Here you can find all layout ids for all supported audio codecs.

**Comment by chaikovskiy99** [comment]
> > > Mine is X515JA-X515JAB, thanks for reply. But later I found Intel smart sound technology isn't supported and any device connected through this will not work.
> > > Once again thanks for EFI 😃 I found this when I completely lost my hope of installing macOS on my laptop. Your EFI worked perfectly for me.
> > 
> > 
> > I have same laptop, I managed to install through official dortania guide, but audio is erratic, it works sometimes, and sometimes it doesn't, layout id 13 also works for me, when it actually works. Also, have you fixed display scaling?
> 
> Do you have exact same model? X515JA-X515JAB? I didn't faced any issues regarding display scalling, it worked fine with this EFI. Small confirmation, do your laptop have C-Media sound card?

I have X515-JAB with IPS panel, this company has really strange naming scheme, there are so many models with this name, some only differing in display quality, like FHD IPS panel with 250 nits of brightness, while others have FHD TN panel with 200 nits of brightness. They have really mad naming scheme. Coming back to the sound card, I have Intel(R) Smart Sound Technology controller. Mine also supports ALC256, but the it works randomly, I have tried all IDs, the problem persists.

**Comment by chaikovskiy99** [comment]
> > > Mine is X515JA-X515JAB, thanks for reply. But later I found Intel smart sound technology isn't supported and any device connected through this will not work.
> > > Once again thanks for EFI 😃 I found this when I completely lost my hope of installing macOS on my laptop. Your EFI worked perfectly for me.
> > 
> > 
> > I have same laptop, I managed to install through official dortania guide, but audio is erratic, it works sometimes, and sometimes it doesn't, layout id 13 also works for me, when it actually works. Also, have you fixed display scaling?
> 
> Just like @ParampreetR, I didn't face any issue regarding display scaling. As for audio issue if you have the same Realtek codec as mine, which is ALC256, you can try another layout id. https://github.com/acidanthera/AppleALC/wiki/Supported-codecs Here you can find all layout ids for all supported audio codecs.

What resolution are you using?

**Comment by Levonhard** [comment]
> > > > Mine is X515JA-X515JAB, thanks for reply. But later I found Intel smart sound technology isn't supported and any device connected through this will not work.
> > > > Once again thanks for EFI 😃 I found this when I completely lost my hope of installing macOS on my laptop. Your EFI worked perfectly for me.
> > > 
> > > 
> > > I have same laptop, I managed to install through official dortania guide, but audio is erratic, it works sometimes, and sometimes it doesn't, layout id 13 also works for me, when it actually works. Also, have you fixed display scaling?
> > 
> > 
> > Just like @ParampreetR, I didn't face any issue regarding display scaling. As for audio issue if you have the same Realtek codec as mine, which is ALC256, you can try another layout id. https://github.com/acidanthera/AppleALC/wiki/Supported-codecs Here you can find all layout ids for all supported audio codecs.
> 
> What resolution are you using?

I'm using 1080p.
Is GPU acceleration enabled in your hackintosh?

**Comment by chaikovskiy99** [comment]
> > > > > Mine is X515JA-X515JAB, thanks for reply. But later I found Intel smart sound technology isn't supported and any device connected through this will not work.
> > > > > Once again thanks for EFI 😃 I found this when I completely lost my hope of installing macOS on my laptop. Your EFI worked perfectly for me.
> > > > 
> > > > 
> > > > I have same laptop, I managed to install through official dortania guide, but audio is erratic, it works sometimes, and sometimes it doesn't, layout id 13 also works for me, when it actually works. Also, have you fixed display scaling?
> > > 
> > > 
> > > Just like @ParampreetR, I didn't face any issue regarding display scaling. As for audio issue if you have the same Realtek codec as mine, which is ALC256, you can try another layout id. https://github.com/acidanthera/AppleALC/wiki/Supported-codecs Here you can find all layout ids for all supported audio codecs.
> > 
> > 
> > What resolution are you using?
> 
> I'm using 1080p. Is GPU acceleration enabled in your hackintosh?

Yes. I have full GPU acceleration. Aren't fonts too small with 1080p resolution? I have correct resolution, but fonts appear too small on 15.6 inch display. When I scale by enabling Hidpi, I get 1440x815 where everything is too big. Looks like you are able to work with small fonts)).

**Comment by chaikovskiy99** [comment]
There isn't any central font size control setting in mac OS, so you either end up scaling your display or increasing the fonts on per app basis, which is tiresome.

**Comment by Levonhard** [comment]
![Captura de Tela 2022-12-19 às 10 50 51](https://user-images.githubusercontent.com/41311859/208440774-da90151e-9fed-4eaf-b59b-78424eef2f70.png)

This is my current font size, didn't set any scale.
Is this the same for you and is this too small for you?

**Comment by chaikovskiy99** [comment]
![Screenshot 2022-12-20 at 08 28 50](https://user-images.githubusercontent.com/4904151/208571687-4e30837f-97c6-4c79-b4a3-29e99bf20e6b.png)
![Screenshot 2022-12-20 at 08 29 30](https://user-images.githubusercontent.com/4904151/208571697-eb5eb037-1988-49ae-9f8c-3bfc608f1f80.png)

**Comment by Levonhard** [comment]
> ![Screenshot 2022-12-20 at 08 28 50](https://user-images.githubusercontent.com/4904151/208571687-4e30837f-97c6-4c79-b4a3-29e99bf20e6b.png)
> ![Screenshot 2022-12-20 at 08 29 30](https://user-images.githubusercontent.com/4904151/208571697-eb5eb037-1988-49ae-9f8c-3bfc608f1f80.png)

this is the Mac default font size. I don't know how to increase
